---
- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
  - name: install apache2 package
    apt:
      name: apache2
  - name: add PHP support for apache
    apt:
      name: libapache2-mod-php
  - name: install apache2 package (redhat)
      dnf:
	name:
	  - sysstat
	  - httpd
          - mardiadb-server
          - apache2
        state: latest
